model:
  name: xgboost
  params:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    subsample: 0.8
    use_label_encoder: false
    eval_metric: logloss
    enable_categorical: true

feature_engineering:
  encoding: no_encoding
